version: "2.0"

dependencies: ./kogito-tooling-project-dependencies.yaml

default:
  build-command:
    current: mvn -e -T1C clean install -DskipTests -Denforcer.skip -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    after:
      upstream: rm -rf ./*
      current: rm -rf ./*

build:
  - project: kiegroup/kie-wb-common
    build-command:
      current: mvn -e -nsu -Dfull -Pwildfly clean install -Denforcer.skip -DskipTests -Prun-code-coverage  -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -am -pl kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime,kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime 
      after: 
        current: echo 'TEST1'
      merge: ['after']

  - project: kiegroup/drools-wb
    build-command:
      current: mvn -e -nsu -Dfull -Pwildfly clean install -Denforcer.skip -DskipTests -Prun-code-coverage  -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -pl drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime -am
      after:
        current: echo 'TEST2'
      merge: ['after']

  - project: kiegroup/kogito-tooling
    build-command:
      before: |
        export EXTERNAL_RESOURCE_PATH__bpmnEditor=../kiegroup_kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/target/kie-wb-common-stunner-bpmn-kogito-runtime
        export EXTERNAL_RESOURCE_PATH__dmnEditor=../kiegroup_kie-wb-common/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/target/kie-wb-common-dmn-webapp-kogito-runtime
        export EXTERNAL_RESOURCE_PATH__scesimEditor=../kigroupo_drools-wb/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/target/drools-wb-scenario-simulation-editor-kogito-runtime
      current: |
        /bin/bash -c "ls .. | grep -v kogito-tooling | grep -v kie-wb-common | grep -v drools-wb | xargs rm -rf"
        rm -rf $HOME/.m2
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        yarn config set network-timeout 1000000
        export DISPLAY=:99.0
        /bin/bash -c "/usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
        /bin/bash -c "echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"
        yarn run init
        yarn run build:prod
        yarn run build:fast
        
        cd packages/online-editor
        yarn run start &
        cd -
        cd packages/chrome-extension-pack-kogito-kie-editors
        yarn run serve-envelope &
        cd -
        sleep 20  
        npx lerna run test:it --stream

